version: '2'
services:
  ojs:
    build: .
    ports:
      - 8001:8081
    links:
      - db
    depends_on:
      - db
    command: "/bin/sh -c '/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf'"
    volumes:
      - ./files:/var/www/html/files
    networks:
      app_net:
        ipv4_address: 172.21.0.2
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: ojs
      POSTGRES_DB: ojs
      POSTGRES_USER: ojs
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      app_net:
        ipv4_address: 172.21.0.3


networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.21.0.0/16
        gateway: 172.21.0.1
