version: '2'
services:
  ojs:
    build: .
    ports:
      - 8001:8081
    links:
      - mysql:db
    depends_on:
      - mysql
    command: "/bin/sh -c '/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf'"
    volumes:
      - ./files:/var/www/html/files
    networks:
      app_net:
        ipv4_address: 172.21.0.2

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ojs
      - MYSQL_USER=ojs
      - MYSQL_PASSWORD=ojs
    networks:
      app_net:
        ipv4_address: 172.21.0.3


networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.21.0.0/16
        gateway: 172.21.0.1
